from singlylinkedlist import LinkedList

linkedList = LinkedList()
print("Initialise linked list:")
linkedList.traverse()
print()

print("Add 3 values:")
linkedList.append(4)
linkedList.append(5)
linkedList.append(6)
linkedList.traverse()
print()

print("Prepend 3 values:")
linkedList.prepend(3)
linkedList.prepend(2)
linkedList.prepend(1)
linkedList.traverse()
print()

print("Find nodes with value:")
print(f"Node with value of 3: {linkedList.find(3)}")
print(f"Node with value of 6: {linkedList.find(6)}")
# print(f"Node with value of 7: {linkedList.find(7)}")
print()

print("Inserting nodes:")
linkedList.insert(10, 3)
linkedList.insert(10, 0)
linkedList.insert(10, linkedList.length() - 1)
linkedList.traverse()
print()

print("Delete all nodes with value 10:")
linkedList.delete(10)
linkedList.delete(10)
linkedList.delete(10)
linkedList.traverse()
print()